// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOKxfnP203zdEx291y7hhYm9QzlkbO2jk',
    appId: '1:249424497337:web:4858ee71e5b6fc960c6968',
    messagingSenderId: '249424497337',
    projectId: 'spytifo-3c62f',
    authDomain: 'spytifo-3c62f.firebaseapp.com',
    storageBucket: 'spytifo-3c62f.firebasestorage.app',
    measurementId: 'G-7EV5QC4721',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXLuoobocUyTTDC-y2KQ3ebP8HSNDa7Is',
    appId: '1:249424497337:android:96ffad0972fc7d550c6968',
    messagingSenderId: '249424497337',
    projectId: 'spytifo-3c62f',
    storageBucket: 'spytifo-3c62f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcoQFCoOftYNsBzCt0-my5SriWt3jZEAU',
    appId: '1:249424497337:ios:0f04aae86e1ad80f0c6968',
    messagingSenderId: '249424497337',
    projectId: 'spytifo-3c62f',
    storageBucket: 'spytifo-3c62f.firebasestorage.app',
    iosBundleId: 'com.example.spytifo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcoQFCoOftYNsBzCt0-my5SriWt3jZEAU',
    appId: '1:249424497337:ios:0f04aae86e1ad80f0c6968',
    messagingSenderId: '249424497337',
    projectId: 'spytifo-3c62f',
    storageBucket: 'spytifo-3c62f.firebasestorage.app',
    iosBundleId: 'com.example.spytifo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOKxfnP203zdEx291y7hhYm9QzlkbO2jk',
    appId: '1:249424497337:web:6591b49afac05ea90c6968',
    messagingSenderId: '249424497337',
    projectId: 'spytifo-3c62f',
    authDomain: 'spytifo-3c62f.firebaseapp.com',
    storageBucket: 'spytifo-3c62f.firebasestorage.app',
    measurementId: 'G-6N7VWBE0LC',
  );
}
